### ISSUE TITLE
incorrect independent variable

### ISSUE THREAD

**Issue by kyawsawhtoon** [learn-co-curriculum/dsc-derivatives-intro#1]
it should be jog(hours): 

def jog(miles):
    return 6*miles
x = np.linspace(0, 3, 100)

plt.plot(x, jog(x))
plt.ylabel("distance in miles")
plt.xlabel("number of hours")
plt.show()

**Comment by jessepisel** [comment]
Howdy @kyawsawhtoon thank you for catching this :wave: . You are correct on this change and I have made your suggested changes with commit ce3df5d43c138788748a84567f1aac39be93188c.

I am closing this issue at this time.
